(clear)
(hint-wire)
(scale (vmul vec1 1))
(define (render n) (cond ((> n 0)
  (colour (rndvec))
  ;(scale (rsndtouch vec1 0.2))
  ;(scale (vector (gh 1) (gh 5) (gh 9)))
  (push)
  (rotate (vector 0 (fmod (* 100 (time)) 360) 0))
  ;(translate (rndvec))
  ;(translate (vector (gh 6) (gh 7) (gh 8)))
  (translate (rsndtouch vec1 0.1))
  (draw-cube)
  (pop)
  (translate (vector 0 1.3 0))
  (render (- n 1)))))

(every-frame (render 5))
